x-pictures-volume: &pictures-volume
  type: bind
  source: ./front/pictures/
  target: /pictures/

services:
  db:
    build: ./db/
    expose:
      - ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file: .env
    restart: on-failure

  api:
    build: ./api/
    expose:
      - ${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file: .env
    volumes:
      - <<: *pictures-volume
    depends_on:
      - db
    restart: on-failure

  front:
    build: ./front/
    ports:
      - "${FRONT_PORT}:80"
    volumes:
      - <<: *pictures-volume
        target: /usr/local/apache2/htdocs/pictures/
    depends_on:
      - api
    restart: on-failure
