volumes:
  pgdata:

x-pictures-volume: &pictures-volume
  type: bind
  source: ./front/pictures/
  target: /${PICTURES_DIR:?}/

services:
  db:
    build: ./db/
    expose:
      - ${DB_PORT:?}
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure

  api:
    build: ./api/
    ports:
      - "${API_LOCAL_PORT:?}:${API_LOCAL_PORT:?}"
    env_file: .env
    volumes:
      - <<: *pictures-volume
    depends_on:
      - db
    restart: on-failure

  front:
    build:
      context: ./front/
      args:
        API_PUBLIC_PORT: ${API_PUBLIC_PORT:?}
        SUPERPOSABLES_SIDE: ${SUPERPOSABLES_SIDE:?}
        PICTURES_DIR: ${PICTURES_DIR:?}
        SUPERPOSABLES_DIR: ${SUPERPOSABLES_DIR:?}
    ports:
      - "${FRONT_LOCAL_PORT:?}:80"
    volumes:
      - <<: *pictures-volume
        target: /usr/local/apache2/htdocs/${PICTURES_DIR:?}/
    depends_on:
      - api
    restart: on-failure
