x-pictures-volume: &pictures-volume
  type: bind
  source: ./front/pictures/
  target: /pictures/

services:
  db:
    build: ./db/
    expose:
      - ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always

# TODO: uncomment this when the project is finished
#  api:
#    build: ./api/
#    expose:
#      - ${API_PORT}
#    ports:
#      - "${API_PORT}:${API_PORT}"
#    volumes:
#      pictures: *pictures-volume
#    depends_on:
#      - db

  front:
    build: ./front/
    ports:
      - "${FRONT_PORT}:80"
    volumes:
      - <<: *pictures-volume
        target: /usr/local/apache2/htdocs/pictures/
    depends_on:
      #- api
      - db # TEMP (only for dev purposes)
