version: "3.7"

x-pictures-volume:
  &pictures-volume
  - type: bind
    source: ./front/pictures/
    target: /pictures/

services:
  db:
    build: ./db/
    expose:
      - ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}

# TODO: uncomment this when the project is finished
#  api:
#    build: ./api/
#    expose:
#      - ${API_PORT}
#    ports:
#      - "${API_PORT}:${API_PORT}"
#    environment:
#      RUST_BACKTRACE: 1
#      ROCKET_ADDRESS: 0.0.0.0
#      ROCKET_PORT: ${API_PORT}
#      ROCKET_SECRET_KEY: 17tu+oEIpQy3OwTKhEDUIhr1HFWyKcb92xzPpLS3t3Y=
#      ROCKET_DATABASES: >
#        {${DB_USER}={
#          url=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_USER}
#        }}
#    volumes:
#      pictures: *pictures-volume
#    depends_on:
#      - db

  front:
    build: ./front/
    ports:
      - "${FRONT_PORT}:80"
    volumes:
      - <<: *pictures-volume
        target: /usr/local/apache2/htdocs/pictures/
    depends_on:
      #- api
      - db # TEMP (only for dev purposes)
