FROM httpd:2.4
COPY ./src/*.html /usr/local/apache2/htdocs/
COPY ./src/*.js /usr/local/apache2/htdocs/
COPY ./src/style/ /usr/local/apache2/htdocs/style/
COPY ./favicon /usr/local/apache2/htdocs/favicon/
COPY ./icons/ /usr/local/apache2/htdocs/icons/
COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf
